parallel-jobs = 1

[YouTube-Morphe]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
excluded-patches = "'Alternative thumbnails' 'Bypass image region restrictions' 'Captions' 'Change form factor' 'Change start page' 'Check watch history domain name resolution' 'Custom branding' 'Custom player overlay opacity' 'Disable DRC audio' 'Disable QUIC protocol' 'Disable Shorts resuming on startup' 'Disable double tap actions' 'Disable layout updates' 'Disable rolling number animations' 'Disable video codecs' 'Double tap to seek' 'Enable debugging' 'Exit fullscreen mode' 'Hide related videos' 'Hide timestamp' 'Loop video' 'Open system share sheet' 'Open videos fullscreen' 'Override YouTube Music actions' 'Play all' 'Reload video' 'Shorts autoplay' 'Spoof app version' 'Spoof device dimensions' 'Spoof video streams' 'Swipe controls'"


[Music-Morphe]
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
included-patches = "'Bypass certificate checks' 'Change header' 'Enable exclusive audio playback' 'Force original audio' 'GmsCore support' 'Hide 'Get Music Premium'' 'Hide music video ads' 'Navigation bar' 'Remove background playback restrictions' 'Sanitize sharing links' 'Theme'"
exclusive-patches = true

